# docker-compose.yml
version: "3.9"

volumes:
  appcal_postgres_data:
    name: appcal_postgres_data
  appcal_pgadmin_data:
    name: appcal_pgadmin_data
  appcal_rabbitmq_data:
    name: appcal_rabbitmq_data

networks:
  appcal_network:
    name: appcal_network
    driver: bridge

services:
  postgres_service:
    image: postgres:latest
    container_name: appcal_postgres_container
    restart: always
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_DB: appcal_db
    volumes:
      - appcal_postgres_data:/var/lib/postgresql
      - ./database/postgres/db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - appcal_network
    ports:
      - "5432:5432"


  pgadmin_service:
    image: dpage/pgadmin4:latest
    container_name: appcal_pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - appcal_pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - appcal_network
    ports:
      - "8080:80"
    depends_on:
      - postgres_service

  rabbitmq_service:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq_container
    restart: on-failure
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
    volumes:
      - appcal_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - appcal_network
    depends_on:
      - postgres_service

  express-image:
    build:
      context: ./express_app # This is the build context (the directory where Dockerfile and app code are located)
      dockerfile: Dockerfile # Specify the Dockerfile (optional if it's named Dockerfile)
    container_name: express_app_container
    restart: on-failure
    ports:
      - "3001:3001"
    volumes:
      - ./express_app:/app
      - /app/node_modules
    networks:
      - appcal_network
    depends_on:
      - rabbitmq_service
      - postgres_service